### ISSUE TITLE
Custom web app id support

### ISSUE THREAD

**Issue by tar500** [ConnectSDK/Connect-SDK-iOS-Google-Cast#3]
GoogleCast web app id is hardcoded to ```kGCKMediaDefaultReceiverApplicationID``` in CastService.m
Shouldn't there be a way to use custom web app id without modifying this project's source code?

**Comment by iadnan** [comment]
Added support for custom web app id .https://github.com/ConnectSDK/Connect-SDK-iOS-Google-Cast/commit/5f454884494e7613870e475926aac7736670d3e4
